### ISSUE TITLE
After seek with keyboard problem

### ISSUE THREAD

**Issue by damaniosif** [OtherCrashOverride/c2play#10]
Hi,

after seek with right arrow of keyboard the video resume to play until reach 1 or 2 seconds before end and it not finishing, Do you know about it?

**Comment by OtherCrashOverride** [comment]
This sounds similar to an issue that was corrected.  Ensure you are using the beta1 branch for testing.  I will see if I can reproduce the issue.

**Comment by damaniosif** [comment]
No I use alpha3

**Comment by damaniosif** [comment]
Is it easy for you to fix it also in alpha3???

**Comment by OtherCrashOverride** [comment]
I checked and the fix should be present in alpha3
https://github.com/OtherCrashOverride/c2play/commit/26e34c8f1b03ab9011669166c83b86361322f0fc

The alpha3 branch is no longer supported since beta1 is now available.

**Comment by damaniosif** [comment]
Hi

I tested with beta1 and the problem is still there.

Thank you.

**Comment by damaniosif** [comment]
If you press pause play or seek jast few seconds before the video end then the error is reproduced. Try it.

**Comment by OtherCrashOverride** [comment]
If it happens with play/pause that helps to narrow down the scope.  What is the media container you are seeing this happen with (avi/mp4/mkv/ts)?

**Comment by OtherCrashOverride** [comment]
I will investigate this further when time permits.

**Comment by OtherCrashOverride** [comment]
This commits displays the media duration making it easier to reliably test and reproduce this issue:
https://github.com/OtherCrashOverride/c2play/commit/cfbfa9a17cf5470231f2a82abd3d5b40a9db2ac7

To reproduce, get the "Duration:" output and use it as a parameter for playback.
./c2play-x11 YourMediaFile.mp4 -t 0.0
Substitute a value less than duration for the "-t" parameter.  Testing shows that if the time is near the end (within seconds) of the stream, playback may not occur or the player may get stuck.

This bug is not trivial to correct.  It can be worked around by testing your media file using the above method and avoiding seeks to durations past a known working duration.

**Comment by OtherCrashOverride** [comment]
I have identified the cause of the lock-ups.  It happens when streams are badly muxed (such as for edits of live tv shows) causing an incorrect stream duration.  Seeking to this duration failed but c2play was not terminated.  This caused the player to continue to wait for data to arrive.  The program will now throw an AVException when this condition happens.

The failure to display the last few seconds of a stream are due to av_seek_frame seeking past the last valid keyframe.  The AVSEEK_FLAG_BACKWARD flag is now always used so that seeking will backup to the last valid key frame.  Since this may be an I frame and not an IDR frame, its possible that nothing will be displayed or garbage will be seen.  This is not a bug since the only valid seek points are IDR frames.  Additionally, the codec extra data is now always sent at the start of a stream making it possible for the hardware to attempt decoding with only I frames.

This commit and the two prior resolve this issue:
https://github.com/OtherCrashOverride/c2play/commit/d2b7264058289e1694791c33cd346c9be15e37e0
